stages:
  - build
  - upload
  - release

variables:
  LATEX_IMAGE: registry.gitlab.com/islandoftex/images/texlive:latest
  REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/resume/0.0.1"
  SRC_FILE: resume.tex
  PDF_FILE: resume.pdf

build:
  stage: build
  image: $LATEX_IMAGE
  script:
    - latexmk -outdir=build -pdf ${SRC_FILE}
  after_script:
    - ls build/
    - echo ${CI_PROJECT_ID}
  artifacts:
    paths:
      - build/

upload:
  stage: upload
  image: curlimages/curl:latest
  script:
    - |
      ls
    - |
      ls build
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file build/${PDF_FILE} "${REGISTRY_URL}/${PDF_FILE}"
      
release:
  # Caution, as of 2021-02-02 these assets links require a login, see:
  # https://gitlab.com/gitlab-org/gitlab/-/issues/299384
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - |
      release-cli create --name "build ${CI_COMMIT_SHORT_SHA}" \
        --assets-link "{\"name\":\"${PDF_FILE}\",\"url\":\"${REGISTRY_URL}/${PDF_FILE}\"}"

